votingproject/dashapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'dashapp'

urlpatterns = [
    #/dashboard/
    url(r'^$', views.TeamList.as_view(), name="dashboard"),
    #/dashboard/female_presenters
    url(r'^female_presenters/$', views.FemaleList.as_view(), name="female_presenters"),
    url(r'^male_presenters/$', views.MaleList.as_view(), name="male_presenters"),
    url(r'^top_teams/$', views.ToptemsDetails.as_view(), name="top_teams"),
    url(r'^top_females/$', views.TopFemales.as_view(), name="top_females"),
    url(r'^top_males/$', views.TopMales.as_view(), name="top_males"),
    #/dashboard/create_team
    url(r'create_team/$', views.CreateTeam.as_view(), name='create_team'),
    url(r'add_female/$', views.AddFemale.as_view(), name='add_female'),
    url(r'add_male/$', views.AddMale.as_view(), name='add_male'),
    #/dashboard/team_pk
    url(r'^(?P<pk>[0-9]+)/$',views.TeamDetails.as_view(),name="team_details"),
    url(r'^(?P<team_id>[0-9]+)/add_member/$',views.add_member,name="add_member"),
    url(r'register/$', views.UserFormView.as_view(), name='register'),
    
]

votingproject/loginapp/urls.py
from django.conf.urls import url
from . import views
app_name="loginapp"

urlpatterns = [
    url(r'^$', views.login_user, name="login_user"),
]

votingproject/votingproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
urlpatterns = [
    path('admin/', admin.site.urls),
    url('dashboard/',include('dashapp.urls')),
    url('voting/',include('voteapp.urls')),
    url('login/',include('loginapp.urls'))
]

votingproject/loginapp/models.py
from django.db import models

# Create your models here.

votingproject/loginapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

# Create your views here.
def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('voteapp:voting')
            else:
                return render(request, 'loginapp/voter_login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'loginapp/voter_login.html', {'error_message': 'Invalid login'})
    return render(request, 'loginapp/voter_login.html')

votingproject/loginapp/templates/loginapp/voter_login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Signin</title>
    {% load staticfiles %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'dashapp/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'dashapp/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet"> 

    <!-- Custom styles for this template -->
    <link href="{% static 'dashapp/css/signin.css' %}" rel="stylesheet"> 

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'dashapp/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

        {% if error_message %}
            <script>alert("{{ error_message }}")</script>
        {% endif %}
        <form class="form-signin"  role="form" action="{% url 'loginapp:login_user'%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
        <input class="form-control" placeholder="Username" id="id_username" maxlength="30" name="username" type="text">
        </div>
        <div class="form-group">
        <input class="form-control" placeholder="Password" id="id_password" maxlength="30" name="password" type="password">
        </div>
        <button type="submit" class="btn btn-lg btn-primary btn-block">Sign in</button>
        </form>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'dashapp/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>