votingproject/dashapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'dashapp'

urlpatterns = [
    #/dashboard/
    url(r'^$', views.TeamList.as_view(), name="dashboard"),
    #/dashboard/female_presenters
    url(r'^female_presenters/$', views.FemaleList.as_view(), name="female_presenters"),
    url(r'^male_presenters/$', views.MaleList.as_view(), name="male_presenters"),
    url(r'^top_teams/$', views.ToptemsDetails.as_view(), name="top_teams"),
    url(r'^top_females/$', views.TopFemales.as_view(), name="top_females"),
    url(r'^top_males/$', views.TopMales.as_view(), name="top_males"),
    #/dashboard/create_team
    url(r'create_team/$', views.CreateTeam.as_view(), name='create_team'),
    url(r'add_female/$', views.AddFemale.as_view(), name='add_female'),
    url(r'add_male/$', views.AddMale.as_view(), name='add_male'),
    #/dashboard/team_pk
    url(r'^(?P<pk>[0-9]+)/$',views.TeamDetails.as_view(),name="team_details"),
    url(r'^(?P<team_id>[0-9]+)/add_member/$',views.add_member,name="add_member"),
    url(r'register/$', views.UserFormView.as_view(), name='register'),
    
]

votingproject/votingproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
urlpatterns = [
    path('admin/', admin.site.urls),
    url('dashboard/',include('dashapp.urls')),
    url('voting/',include('voteapp.urls')),
    url('login/',include('loginapp.urls'))
]

votingproject/dashapp/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.

class Team(models.Model):
    team_name = models.CharField(max_length=250)
    team_project = models.CharField(max_length=250)
    bio = models.TextField(max_length=1000)
    vote_count = models.PositiveIntegerField(default=0)
    is_voted = models.BooleanField(default=False)

    def __str__(self):
        return self.team_name

    def get_absolute_url(self):
        return reverse('dashapp:team_details', kwargs={'pk':self.pk})

class Members(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    fName = models.CharField(max_length=50)
    lName = models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('dashapp:team_details', kwargs={'pk':self.pk})

class MalePresenter(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    fName = models.CharField(max_length=50)
    lName = models.CharField(max_length=50)
    vote_count = models.PositiveIntegerField(default=0)
    is_voted = models.BooleanField(default=False)

    def __str__(self):
        return self.fName+' '+self.lName
    
    def get_absolute_url(self):
        return reverse('dashapp:female_presenters')
    
class FemalePresenter(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    fName = models.CharField(max_length=50)
    lName = models.CharField(max_length=50)
    vote_count = models.PositiveIntegerField(default=0)
    is_voted = models.BooleanField(default=False)

    def __str__(self):
        return self.fName+' '+self.lName
    
    def get_absolute_url(self):
        return reverse('dashapp:female_presenters')
    

votingproject/dashapp/forms.py
from django import forms
from dashapp.models import Team, Members
from django.contrib.auth.models import User

class TeamForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Team
        fields = ['team_name','team_project','bio']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['first_name','last_name','username','email', 'password']

class MemberForm(forms.ModelForm):

    class Meta:
        model = Members
        fields = ['fName','lName']

votingproject/dashapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from dashapp.models import Team, Members, FemalePresenter, MalePresenter
from dashapp.forms import TeamForm, MemberForm
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from dashapp.forms import UserForm
from django.contrib.auth import login, authenticate, logout
from django.views.generic import View

# Create your views here.

class TeamList(ListView):
    template_name = 'dashapp/teams.html'
    context_object_name = 'all_teams'
    def get_queryset(self):
        return Team.objects.all()

class FemaleList(ListView):
    template_name = 'dashapp/female_presenters.html'
    context_object_name = 'all_females'
    def get_queryset(self):
        return FemalePresenter.objects.all()

class MaleList(ListView):
    template_name = 'dashapp/male_presenter.html'
    context_object_name = 'all_males'
    def get_queryset(self):
        return MalePresenter.objects.all()

class ToptemsDetails(ListView):
    template_name = 'dashapp/top_teams.html'
    context_object_name = 'top_teams'
    def get_queryset(self):
        return Team.objects.order_by('-vote_count')[:5]                 #orderby votecounts top 5

class TopFemales(ListView):
    template_name = 'dashapp/top_females.html'
    context_object_name = 'top_females'
    def get_queryset(self):
        return FemalePresenter.objects.order_by('-vote_count')[:5]                 #orderby votecounts top 5
    
class TopMales(ListView):
    template_name = 'dashapp/top_males.html'
    context_object_name = 'top_males'
    def get_queryset(self):
        return MalePresenter.objects.order_by('-vote_count')[:5]                 #orderby votecounts top 5



class TeamDetails(DetailView):
    model = Team
    template_name = 'dashapp/team_detail.html'

class CreateTeam(CreateView):
    model = Team
    fields = ['team_name', 'team_project', 'bio']


class AddFemale(CreateView):
    model = FemalePresenter
    fields = ['team', 'fName', 'lName']


class AddMale(CreateView):
    model = MalePresenter
    fields = ['team', 'fName', 'lName']


class UserFormView(View):
    form_class=UserForm
    template_name = 'dashapp/voter_form.html'

    #display blank form
    def get(self, request):
        form = self.form_class(None)
        context = {
            'form':form
        }
        return render(request, self.template_name, context)
    
    #process form data
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            #cleaned normalize data
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user.set_password(password)
            user.save()
        #returns User objects if credentials are correct
        user = authenticate(username=username, password=password)
        context = {
        'form': form,
        'success_message':'user.username added'
        }
        if user is not None:

            if user.is_active:
                login(request, user)
                return redirect('voteapp:voting') 
        
        return render(request, self.template_name,context) 


def add_member(request, team_id):
    form = MemberForm(request.POST or None)
    team = get_object_or_404(Team, pk=team_id)

    if form.is_valid():
        context = {
        'team': team,
        'form': form,
        }
        members = form.save(commit=False)
        members.team = team
        members.save()
        return render(request, 'dashapp/team_detail.html', context)
        
    context = {
        'team': team,
        'form': form,
    }

    return render(request, 'dashapp/members_form.html', context)

votingproject/dashapp/templates/dashapp/ajaxxx_practice.html
<!DOCTYPE html>
<html>
    <head>
        <title>JSON and AJAX</title>
    </head>

<body>
    <header>
        <h1>JSON and AJAX</h1>
        <button id="btn">Fetch Infor for 3 New Animals</button>
    </header>
    <div id="animal-info"></div>
    <script src="js/main.js"></script>
</body>
</html>

votingproject/dashapp/templates/dashapp/dashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    {% load staticfiles %}
    <link rel="icon" href="{% static 'dashapp/img/cpu.ico' %}">

    <title>{% block title %}Computer Engineering Exhibit Voting System{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'dashapp/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'dashapp/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'dashapp/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- Custom styles for this template -->
    <link href="{% static 'dashapp/css/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'dashapp/css/signin.css' %}" rel="stylesheet"> 

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'dashapp:dashboard' %}">Computer Engineering Exhibit Voting System</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'dashapp:register' %}">Registration</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">{{ user.username }}</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="{% url 'dashapp:dashboard' %}">Teams</a></li>
            <li><a href="{% url 'dashapp:male_presenters' %}">Male Presentors</a></li>
            <li><a href="{% url 'dashapp:female_presenters' %}">Female Presentors</a></li>
            <li><a href="#">Voters</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="{% url 'dashapp:top_teams' %}">Top 5 teams</a></li>
            <li><a href="{% url 'dashapp:top_males' %}">Top 5 Male Presenters</a></li>
            <li><a href="{% url 'dashapp:top_females' %}">Top 5 Female Presenters</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

                  {% block content %}
                  {% endblock %}
          
        </div>
      </div>
    
      <hr> 
      <footer>
          <p>&copy; 2016 Company, Inc.</p>
      </footer>
  
    </div>

    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'dashapp/js/jquery.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'dashapp/js/bootstrap.min.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'dashapp/js/holder.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'dashapp/js/ie10-viewport-bug-workaround.js' %}"></script> 
  </body>
</html>

votingproject/dashapp/templates/dashapp/female_presenters.html
{% extends 'dashapp/dashboard.html' %}
{% block content %}
    <h2 class="sub-header">Teams</h2>
        <div class="row">
            <div class="row placeholders">
                {% for female in all_females %}
                    <div class="col-xs-6 col-sm-3 placeholder">
                        {% load staticfiles %}
                        <img src="{% static 'dashapp/img/ivos.jpg' %}" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                        <h4>{{ female.fName }} {{ female.lName }}</h4>
                        <span class="text-muted">{{ female.team }}</span>
                        </div>
                {% endfor %}
            </div>
        
            <div class="col-sm-offset-9 col-sm-1"><a href="{% url 'dashapp:add_female' %}"><input type="submit" value="Add Female Presenter" class="btn btn-lg btn-danger"></a></div>
        </div>
{% endblock %}

votingproject/dashapp/templates/dashapp/femalepresenter_form.html
{% extends "dashapp/dashboard.html" %}
{% block title %}Add Member{% endblock %}
{% block content %}

<div class="container">

    <div class="row">
    {% if error_message %}
        <script>
            alert('{{ error_message }}');
        </script>
    {% endif %}
          <div class="col-md-8 order-md-1">
            <h2 class="mb-3">Add Female Presenter</h2>
                  <form class="form-horizontal form-signin" action="#" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}
                      {% include 'dashapp/form-template.html' %}
                      <div class="form-group">
                          <div class="col-sm-offset-2 col-sm-10">
                              <button type="submit" class="btn btn-danger">Submit</button>
                          </div>
                      </div>
                  </form>
          </div>  
    </div>
 </div>

{% endblock %}

votingproject/dashapp/templates/dashapp/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
           <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
        {% if field == 'password' %}
            <label class="control-label col-sm-2">{{ field.label_tag }}</label>
            <div class="col-sm-10" ><input class="form-control" type="password" value="{{ field }}"></div>
        {% endif %}
    </div>
{% endfor %}

votingproject/dashapp/templates/dashapp/male_presenter.html
{% extends 'dashapp/dashboard.html' %}
{% block content %}
    <h2 class="sub-header">Teams</h2>
        <div class="row">
            <div class="row placeholders">
                {% for male in all_males %}
                    <div class="col-xs-6 col-sm-3 placeholder">
                        {% load staticfiles %}
                        <img src="{% static 'dashapp/img/ivos.jpg' %}" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                        <h4>{{ male.fName }} {{ male.lName }}</h4>
                        <span class="text-muted">{{ male.team }}</span>
                        </div>
                {% endfor %}
            </div>
            <div class="col-sm-offset-9 col-sm-1"><a href="{% url 'dashapp:add_male' %}"><input type="submit" value="Add Male Presenter" class="btn btn-lg btn-danger"></a></div>
        </div>
{% endblock %}

votingproject/dashapp/templates/dashapp/malepresenter_form.html
{% extends "dashapp/dashboard.html" %}
{% block title %}Add Member{% endblock %}
{% block content %}

<div class="container">

    <div class="row">
    {% if error_message %}
        <script>
            alert('{{ error_message }}');
        </script>
    {% endif %}
          <div class="col-md-8 order-md-1">
            <h2 class="mb-3">Add Male Presenter</h2>
                  <form class="form-horizontal form-signin" action="#" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}
                      {% include 'dashapp/form-template.html' %}
                      <div class="form-group">
                          <div class="col-sm-offset-2 col-sm-10">
                              <button type="submit" class="btn btn-danger">Submit</button>
                          </div>
                      </div>
                  </form>
          </div>  
    </div>
 </div>

{% endblock %}

votingproject/dashapp/templates/dashapp/members_form.html
{% extends "dashapp/dashboard.html" %}
{% block title %}Add Member{% endblock %}
{% block content %}

<div class="container">

    <div class="row">
    {% if error_message %}
        <script>
            alert('{{ error_message }}');
        </script>
    {% endif %}
          <div class="col-md-8 order-md-1">
            <h2 class="mb-3">Add Member</h2>
                  <form class="form-horizontal form-signin" action="#" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}
                      {% include 'dashapp/form-template.html' %}
                      <label>Male Presenter<input type="radio" value="Male Presenter"></label>
                      <label>Female Presenter<input type="radio" value="Female Presenter"></label><br>
                      <div class="form-group">
                          <div class="col-sm-offset-2 col-sm-10">
                              <button type="submit" class="btn btn-danger">Submit</button>
                          </div>
                      </div>
                  </form>
          </div>  
    </div>
 </div>

{% endblock %}

votingproject/dashapp/templates/dashapp/team_detail.html
{% extends 'dashapp/dashboard.html' %}
{% block content %}
<div class="row">
    
        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="row placeholders">
                <div class="panel panel-default">
                    <div class="panel-body">
                                {% load staticfiles %}
                                <img class="img-thumbnail md-margin-bottom-10" src="{% static 'dashapp/img/ivos.jpg' %}" alt="">  
                        <h3>{{ team.team_name }}</h3>
                    </div>
                </div>
            </div>
        </div>
    

    <div class="col-sm-8 col-md-9">

        <div class="panel panel-default">
            <div class="panel-body">
                <h2>{{ team.team_project }}</h2>
                        <hr>
                <p>{{ team.bio }}</p>
            </div>
        </div>

    </div>
</div>
<div class="row">
    <h1 class="page-header">Members</h1>
        <div class="row placeholders">
                {% for member in team.members_set.all %}
                    <div class="col-sm-100 col-md-2">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                        {% load staticfiles %}
                                        <img class="img-thumbnail md-margin-bottom-10" src="{% static 'dashapp/img/ivos.jpg' %}" alt="">  
                                <h5>{{ member.fName }} {{ member.lName }}</h5>
                            </div>
                        </div>
                    </div>
                {% endfor %}
        </div>
        <div class="col-sm-offset-10 col-sm-1"><a href="{% url 'dashapp:add_member' team.id %}"><input type="submit" value="Add Member" class="btn btn-lg btn-danger"></a></div>
</div>

{% endblock %}

votingproject/dashapp/templates/dashapp/team_form.html
{% extends "dashapp/dashboard.html" %}
{% block title %}Add Team{% endblock %}
{% block content %}

<div class="container">

    <div class="row">
    {% if error_message %}
        <script>
            alert('{{ error_message }}');
        </script>
    {% endif %}
          <div class="col-md-8 order-md-1">
            <h2 class="mb-3">Add Team</h2>
                  <form class="form-horizontal form-signin" action="#" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}
                      {% include 'dashapp/form-template.html' %}
                      <div class="form-group">
                          <div class="col-sm-offset-2 col-sm-10">
                              <button type="submit" class="btn btn-danger">Submit</button>
                          </div>
                      </div>
                  </form>
          </div>  
    </div>
 </div>

{% endblock %}

votingproject/dashapp/templates/dashapp/top_females.html
{% extends 'dashapp/dashboard.html' %}
{% block content %}
    <h2 class="sub-header">Teams</h2>
        <div class="row">
            <div class="row placeholders">
                {% for female in top_females %}
                    <div class="col-xs-6 col-sm-3 placeholder">
                        {% load staticfiles %}
                        <img src="{% static 'dashapp/img/ivos.jpg' %}" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                        <h4>{{ female.fName }} {{ female.lName }}</h4>
                        <span class="text-muted">{{ female.vote_count }}</span>
                        </div>
                {% endfor %}
            </div>
        </div>
{% endblock %}

votingproject/dashapp/templates/dashapp/top_males.html
{% extends 'dashapp/dashboard.html' %}
{% block content %}
    <h2 class="sub-header">Teams</h2>
        <div class="row">
            <div class="row placeholders">
                {% for male in top_males %}
                    <div class="col-xs-6 col-sm-3 placeholder">
                        {% load staticfiles %}
                        <img src="{% static 'dashapp/img/ivos.jpg' %}" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                        <h4>{{ male.fName }} {{ male.lName }}</h4>
                        <span class="text-muted">{{ male.vote_count }}</span>
                        </div>
                {% endfor %}
            </div>
           
        </div>
{% endblock %}

votingproject/dashapp/templates/dashapp/top_teams.html
{% extends 'dashapp/dashboard.html' %}
{% block content %}
    <h2 class="sub-header">Teams</h2>
        <div class="row">
            <div class="row placeholders">
                {% for team in top_teams %}
                    <div class="col-xs-6 col-sm-3 placeholder">
                        {% load staticfiles %}
                        <a href="{% url 'dashapp:team_details' team.id %}">
                        <img src="{% static 'dashapp/img/ivos.jpg' %}" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                        </a>
                        <h4>{{ team.team_name }}</h4>
                        <span class="text-muted">Votes: {{team.vote_count}}</span>
                        </div>
                {% endfor %}
            </div>
        
            <div class="col-sm-offset-10 col-sm-1"><a href="{% url 'dashapp:create_team' %}"><input type="submit" value="Add Team" class="btn btn-lg btn-danger"></a></div>
        </div>
{% endblock %}

votingproject/dashapp/templates/dashapp/voter_form.html
{% extends "dashapp/dashboard.html" %}
{% block title %}Add Team{% endblock %}
{% block content %}

<div class="container">

    <div class="row">
    {% if error_message %}
        <script>
            alert('{{ error_message }}');
        </script>
    {% endif %}
          <div class="col-md-8 order-md-1">
            <h2 class="mb-3">Register</h2>
                  <form class="form-horizontal" action="#" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}
                      {% include 'dashapp/form-template.html' %}
                      <div class="form-group">
                          <div class="col-sm-offset-2 col-sm-10">
                              <button type="submit" class="btn btn-danger">Submit</button>
                          </div>
                      </div>
                  </form>
          </div>  
    </div>
 </div>

{% endblock %}